.gitignore, setup.py
Fixes #6 
Wheels are now bound to any version of Python 3 and the platform on which the wheel is built.
=> Wheels are no longer bound to CPython

README.md, azure-pipelines.yml, dev-requirements.txt, examples/triangle.py, setup.py, wgpu/backend/rs.py, wgpu/resources/wgpu.h
These are all the fixes I had to apply while trying to run the Qt triangle example on Linux, python 3.6.
This PR can be merged, though currently the examples crash on the python-shader compilation, see related PR https://github.com/almarklein/python-shader/pull/9
=> Various fixes

README.md, wgpu/backend/rs.py, wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/qt.py, wgpu/gui/tk.py
* Adds methods to get the display id on glfw, and a generic approach that uses the X11 lib via ctypes.
* Updates readme.
* Rename canvas classes and provide an alias with a common name. That way you can see from the class what GUI backend is wrapped.
Closes #28, except:
* Does not work for tk for some reason.
* On Wayland only glfw works, because I don't know (yet) how to get the display id from Wayland.
=> Linux support

azure-pipelines.yml, dev-requirements.txt, setup.py
* Run linting on one platform to save some time
* Use auditwheel on Linux
* Build sdist on Linux
* Test installing wheels and sdists from temp folder so we can catch problems like in #38 in CI
* Include `LICENSE` file in built package
* Ensure binaries are not included in sdist
* Pin wheel==0.31.1, see https://github.com/pypa/auditwheel/issues/102
* Don't include the LICENSE file in the license kwarg, see https://github.com/pypa/setuptools/issues/1390
* For now, release step removes linux wheels just before uploading since they are not manylinux1 compliant
Closes #38
=> CI sdist and manylinux1 support

codegen-script.py, dev-requirements.txt, download-wgpu-native.py, examples/compute_noop.py, examples/triangle.py, examples/triangle_glfw.py, examples/triangle_glfw_asyncio.py, examples/triangle_qt.py, examples/triangle_tk.py, setup.py, tests/test_api.py, tests/testutils.py, wgpu/__init__.py, wgpu/_coreutils.py, wgpu/_parsers.py, wgpu/backend/js.py, wgpu/backend/rs.py, wgpu/base.py, wgpu/gui/base.py, wgpu/gui/flexx.py, wgpu/gui/glfw.py, wgpu/gui/qt.py, wgpu/gui/tk.py, wgpu/resources/codegen_report.md, wgpu/utils/__init__.py, wgpu/utils/_compute.py, wgpu/utils/_device.py
Closes #57 
* flags: name is CamelCase, field names are UPPERCASE, values are int.
* enums: name is CamelCase, field names are snake_case, values are 'like-this'.
* structs: their fields are the function arguments, so we never refer them by name.
* function args: name is snake_case. 
* function names: name is snake_case.
=> Convert API to snake_case

dev-requirements.txt, wgpu/backends/rs.py, wgpu/gui/glfw.py, wgpu/gui/tk.py
Here is the work we did on calling objective-c methods with ctypes, to replicate the example code from wgpu-native. Works for Qt and GLFW.
Closes #29
=> Add support for creating wgpu surface on macOS

examples/compute_noop.py, tests/renderutils.py, tests/test_compute.py, tests/test_rs_render.py, wgpu/backends/rs.py, wgpu/resources/codegen_report.md
These new tests actually fail in the lib shipped with the library, because the `BufferUsage.INDIRECT` enum was [changed at some point](https://github.com/gfx-rs/wgpu/pull/468/files). It looks like
the .h file that we use does not precisely match the library. Eek!
Anyway, let's just merge this, and update to the latest wgpu-native.
=> Implement indirect drawing

tests/test_rs_render_tex.py
We weren't using any of the `python_shader.InputResource(` classes (which I plan to remove soon). So no action is needed. Just cleaning up one module a bit.
=> Use shader resource more consistenly (per module).

examples/triangle_glfw.py, examples/triangle_glfw_asyncio.py, tests/test_gui_glfw.py, wgpu/gui/base.py, wgpu/gui/flexx.py, wgpu/gui/glfw.py, wgpu/gui/qt.py
Closes #63 
* For qt this is easy, because it's an alias for `update()`.
* For glfw it's more involved, because glfw does not provide an event loop. So I've made a function that one must call from your glfw mainloop, which will redraw all canvases that are invalidated.
* Updated the glfw tests (they check that multiple events or draw requests result in a single draw)
* The glfw example has a more sophisticated event loop that does not turn your laptop into a heater,
=> Implement request_draw

codegen-script.py, examples/triangle.py, tests/test_api.py, tests/test_rs_basics.py, wgpu/backends/js.py, wgpu/backends/rs.py, wgpu/base.py, wgpu/utils/_device.py
The `request_adapter` in wgpu-native now supports passing the surface id, so that we can make sure that the returned adapter is actually compatible with that (or such type of) surface.
I considered a few options to express this in the API, and this seems to be the most straightforward, even though it makes the API deviate from WebGPU somewhat (because in WebGPU the browser knows the surface id, so the user does not need pass it). Made it a required argument, so that it's obvious when it's set to None.
It's quite liberating that in an API that's low-level, we can afford to be a bit verbose at times :)
=> Allow passing canvas to request_adapter

docs/guide.rst, tests/renderutils.py, tests/test_gui_glfw.py, tests/test_rs_basics.py, tests/test_rs_compute_tex.py, wgpu/backends/rs.py, wgpu/base.py
This adds support for debug groups and markers. I haven't been able to actually see them in RenderDoc, but that is likely because I am missing something else. The C-api of these calls don't leave much room to do something wrong. So we might need to update the guide on debugging when we know a bit more about this.
=> Debug markers

.gitignore, tests/test_rs_render_tex.py, wgpu/base.py
Closes #73 
So the problem appeared to be the `compare` arg in `create_sampler`. It apparently must be set to "undefined". Except ... there is no `wgpu.CompareFunction.undefined`. Fortunately, we can just set it to zero for now.
=> Fix grayscale texture render tests

codegen-script.py, examples/triangle.py, tests/renderutils.py, tests/test_gui_glfw.py, tests/test_rs_compute_tex.py, tests/test_rs_render.py, tests/test_rs_render_tex.py, wgpu/_parsers.py, wgpu/backends/rs.py, wgpu/base.py, wgpu/resources/codegen_report.md
Closes #90 
* Changed the parsing of IDL to take care of default values. 
* Document the default values in `base.py`
* Implement the default values of sub-arguments (dicts) in `rs.py`
* The most notable api change is that we no longer have `texture.create_default_view()`. Instead you call `texture.create_view()` without arguments.
=> More defaults

wgpu/backends/rs.py
I saw some odd behavior, which after some searching seemed to be due to the memory of ctypes object being reclaimed by Python while Rust was still accessing it.
There were some Rust panics that happened inconsistently, and with an error message comparing two values that I was pretty sure where correct. These seem to be gone with these changes.
It also makes the core a bit more explicit about the use of a pointer to a struct vs a "value struct".
=> Prevent premature cleanup

CHANGELOG.md, codegen-script.py, docs/guide.rst, examples/compute_noop.py, examples/cube_glfw.py, tests/renderutils.py, tests/test_api.py, tests/test_compute.py, tests/test_rs_basics.py, tests/test_rs_compute_tex.py, tests/test_rs_render.py, wgpu/backends/rs.py, wgpu/base.py, wgpu/resources/codegen_report.md, wgpu/utils/_compute.py
=> Writing to buffer and texture

docs/guide.rst, wgpu/backends/rs.py
=> Enable tracing in rs backend

docs/reference_gui.rst, examples/cube_glfw.py, examples/triangle.py, tests/renderutils.py, tests/test_gui_glfw.py, wgpu/gui/base.py, wgpu/gui/flexx.py, wgpu/gui/glfw.py, wgpu/gui/qt.py
Closes #101 
The `canvas.request_draw()` method can now be given a callable, which will be used to draw the frame. This way there is no need to set `canvas.draw_frame`. Less API!
The argument is optional, which means it can be called once with the drawing function, and later it can be called from code that simply wants to schedule a new draw and may not be aware of the drawing function. Plus it makes things backwards compatible.
=> Request draw

wgpu/backends/rs.py, wgpu/base.py
=> Add size property to texture view

download-wgpu-native.py, wgpu/backends/rs.py
Closes #108
With this change, we package both the release and the debug build of wgpu-native and allow users to load the debug build by setting the environment variable `WGPU_DEBUG=1`
=> debug mode via WGPU_DEBUG

examples/cube_glfw.py, examples/triangle_glfw.py, wgpu/gui/glfw.py, wgpu/gui/qt.py
This gets things running a bit better on Wayland. Things are still far from great, that is mostly due to Wayland or Glfw or the integration between the two.
* Can now run glfw examples.
* Still no Qt yet.
* Fixed recursion error.
* Fixed weird window sizing behavior (might be an issue specific to hidpi screens on Wayland).
* In the examples, prevent glfw from shutting down on Wayland warnings.
=> Improve wayland support ... a bit

examples/compute_noop.py, tests/test_compute.py, tests/test_gui_glfw.py, tests/test_rs_basics.py, wgpu/gui/base.py, wgpu/utils/_compute.py
* Fix all occurrences of `GlobalInvocationid` to type it as `ivec3` instead of `i32`.
* Fix glfw tests on Linux
* Change `compute_with_buffers()` so that buffers not marked for output are readonly in the shader.
=> Fix usage of GlobalInvocationid

setup.py, wgpu/gui/qt.py
GLFW has an inherent different loop, where you basically need to write the mainloop yourself, and this is where you'd implement FPS limiting. See the `triangle_glfw.py` example.
=> Limit FPS for request_draw in Qt

examples/triangle_wxpython.py, wgpu/gui/wxpython.py
Obviously this is not fully implemented, but It's a  start. 
I had some questions about the usage of the qt timer and how that should be translated into wxpython. I am also having a hard time figuring out how get a relevant value for ``get_display_id``. Not sure if other methods are needed as well.
=> add initial wxpython window support

codegen/apipatcher.py, wgpu/_coreutils.py, wgpu/base.py, wgpu/resources/codegen_report.md
The WebGPU spec does not expose properties like `buffer.size`. It is recognized that these are very useful though, and there are discussions to some let the API expose them. See e.g. https://github.com/gpuweb/gpuweb/issues/1498.
Since we also make use of some of these in pygfx, I think it makes sense to (for now) deviate from the WebGPU API.
=> Mark props as @apidiff.add

wgpu/backends/rs.py, wgpu/base.py, wgpu/resources/codegen_report.md
This allows consuming WGSL in addition to SpirV.
I'm having some trouble rewriting the examples though, and the error messages are not very helpful, e.g.:
```
Running script: "C:\dev\pylib\wgpu\examples\triangle_glfw.py"
|	[[stage(vertex)]]
>	fn vs_main([[builtin(vertex_index)]] index: u32) -> [[builtin(position)]] vec4<f32> {
|	             ^
thread '<unnamed>' panicked at 'Parsing', src\device.rs:694:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm having more luck by using Naga to compile some wgsl to spirv and then using that. This suggests that we may just need a newer version of wgpu-native that has a newer naga. But even then, arrays seem problematic, or I am doing them wrong.
We can merge this as-is and continue when we've updated to a more …
=> Add support for WGSL

codegen/rspatcher.py, tests/test_rs_render_tex.py, wgpu/backends/rs.py, wgpu/backends/rs_mappings.py, wgpu/base.py, wgpu/resources/codegen_report.md, wgpu/resources/wgpu.h
This makes it possible for us to:
* Enable a feature so that float32 textures can still be filtered by the sampler.
* Force vulkan to prevent dx12 being selected.
* Obtain adapter properties so we can see what hardware and backend is selected via `adapter.properties`.
* Includes a small fix in the docs wrt stencil front/back.
=> Update to wgpu-native 0.8.0.2

wgpu/backends/rs.py
This makes sure that on other platforms than Windows any available backend is picked.
=> Force backend by WGPU_BACKEND_TYPE env var

examples/triangle.py, tests/test_gui_base.py, wgpu/backends/rs.py, wgpu/base.py, wgpu/gui/base.py
This makes it possible to write Canvas classes that do not render to a screen, but instead get a texture on each draw, which can be processed  in whatever way makes sense.
This paves the way for e.g. a Jupyter widget.
Note that the WebGPU API for CanvasContext and GPUChain has changed (they are merged into a GPUPresentContext). We should update accordingly soon, because that might affect the API a bit.
=> Implement support for off-screen canvases

codegen/apipatcher.py, codegen/apiwriter.py, codegen/idlparser.py, codegen/rspatcher.py, docs/reference_gui.rst, docs/reference_wgpu.rst, examples/cube_glfw.py, examples/triangle.py, tests/renderutils.py, tests/test_api.py, tests/test_gui_base.py, tests/test_gui_glfw.py, wgpu/backends/rs.py, wgpu/backends/rs_mappings.py, wgpu/base.py, wgpu/enums.py, wgpu/gui/__init__.py, wgpu/gui/base.py, wgpu/gui/offscreen.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.idl, wgpu/structs.py
* The swap-chain class has been removed. This object was used as a context manager.
One should now use the present context object instead (see below). The
drawn result is now automatically presented to the screen at the end of a draw event.
* The `canvas.configure_swap_chain()` method has been removed. Instead,
`canvas.get_context()` should be used, to obtain a present context.
* The new `GPUPresentationContext` class can be `configure()`'d, and a texture can be obtained via
`context.get_current_texture()`.
* Adds `WgpuOffscreenCanvas` to support off-screen rendering while using a canvas API.
* The `adapter.request_device()` method has its arguments `non_guaranteed_features` and `non_guaranteed_limits`
replaced with `required_features` and `required_limits`.
* The enum field …
=> Update to latest webgpu

.github/workflows/ci.yml, examples/triangle.py, setup.cfg, tests/test_compute.py, tests/test_gui_glfw.py, tests/test_rs_basics.py, tests/test_rs_render.py, tests/test_rs_render_tex.py, tests/testutils.py, wgpu/backends/rs.py, wgpu/backends/rs_mappings.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.h, wgpu/resources/wgpu.h
The wgpu-native has bumped its version of wgpu-core and Naga. The only changes that matter to us are that Naga is a bit more strict with indexing (can't index into arrays created with `let`, but must use `var` instead).
=> Updates for latest wgpu-native

CHANGELOG.md, codegen/rspatcher.py, docs/reference_wgpu.rst, examples/compute_noop.py, examples/cube_glfw.py, tests/test_compute.py, tests/test_gui_base.py, tests/test_gui_glfw.py, tests/test_rs_basics.py, tests/test_rs_compute_tex.py, tests/test_rs_render_tex.py, wgpu/backends/rs.py, wgpu/backends/rs_mappings.py, wgpu/base.py, wgpu/enums.py, wgpu/flags.py, wgpu/gui/base.py, wgpu/gui/offscreen.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.idl, wgpu/structs.py
=> Update to latest webgpu spec

README.md, docs/reference_gui.rst, examples/triangle.py, wgpu/gui/base.py, wgpu/gui/jupyter.py, wgpu/gui/offscreen.py
Closes #176
I'm going to leave this open until I've updated pygfx, so I can make sure that it works well for pygfx too.
=> Jupyter canvas

wgpu/backends/rs.py
I want to avoid that users need to set an env var in order to make things work.
=> On Windows force Vulkan by default for now

examples/cube.py, examples/triangle.py
This is cleaner and shorter, and avoids the (hopefully temporary) bug described in https://github.com/pygfx/pygfx/issues/219.
=> Use queue.write_texture instead of copy_to_texture with a temp buffer

wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/jupyter.py, wgpu/gui/qt.py, wgpu/gui/wx.py
This puts most of the logic regarding limiting FPS into the base canvas class. The GUI implementations only have to take care of delaying the request for a new draw in the gui-specific way.
This PR also implements this for Jupyter.
=> Generic implementation of max fps

wgpu/gui/auto.py, wgpu/gui/glfw.py
* Suppress the "during the handling of the above exception ...".
* Some more instructions for Linux.
* Deal with the fact that some glfw functions are not always available.
=> Better glfw import error message

docs/conf.py, wgpu/gui/glfw.py, wgpu/gui/jupyter.py
See https://github.com/pygfx/pygfx/issues/223
New API implemented for glfw and jupyter canvases:
```python
canvas.add_event_handler(callback, *types)
canvas.remove_event_handler(callback, *types)
@canvas.add_event_handler(*types)
def callback(event):
...
```
Where `type` can be any event from [the spec](https://jupyter-rfb.readthedocs.io/en/latest/events.html) and callbacks should be callables receiving an event object.
=> Add event pubsub for glfw and jupyter canvas

wgpu/gui/glfw.py
The windows for GLFW are HUGE! Like 4x too big, which can be explained because we probably did a division where we should have done a multiplication. Also see the comment a few lines up.
=> Fix glfw window size on mac

wgpu/gui/qt.py
By default, Qt widgets do not receive mouse move events when no button is pressed. In order to make sure that mouse move events are tracked, I had to enable mouse tracking for both the `QWgpuWidget` *and* the `QWgpuCanvas`.
=> Emit mouse_move events in Qt when no button is pressed

wgpu/gui/qt.py
Calling super in `mouseDoubleClickEvent` makes sure that the mousePressEvent is called as well.
=> Fix mouse press events not coming through on double clicks

wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/jupyter.py, wgpu/gui/qt.py
Closes https://github.com/pygfx/pygfx/issues/264
The `WgpuAutoGui` implements a method `_handle_event_rate limited()` - as opposed to `handle_event()` - that can be used to rate limit events.
This also refactors the exception logging mechanism to make it generally usable, as a context manager. It was previously only used for the draw handler. Now it's used for events, and we could use it in pygfx.
=> Apply rate limits for events

README.md, codegen/rspatcher.py, examples/compute_noop.py, examples/cube.py, examples/triangle.py, tests/test_compute.py, tests/test_gui_glfw.py, tests/test_rs_basics.py, tests/test_rs_compute_tex.py, tests/test_rs_render.py, tests/test_rs_render_tex.py, wgpu/backends/rs.py, wgpu/backends/rs_helpers.py, wgpu/backends/rs_mappings.py, wgpu/base.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.h, wgpu/resources/wgpu.h
Todo:
Then:
* Some tests that previously failed on Metal now run fine.
* Better error logging using the new callbacks in wgpu-native.
* WGSL syntax changes (see below). Prettier, but some work to change all our shaders.
* All destructors (drop methods) are now working as they should.
* I tried to revive Wayland support, no luck yet.
* Shaders now use `@xx(yy)` instead of `[[xx(yy)]]`, e.g. `@stage(vertex)`.
* Structs now separate items using `,` instead of `;`.
* Buffers bound as arrays don't need to be defined via a struct anymore! 🥳
=> Update to wgpu-native

wgpu/gui/offscreen.py
It seems the example tests don't actually draw a frame. This change should fix that.
=> ensure at least one frame is drawn when using offscreen canvas

docs/conf.py, docs/reference.rst, docs/reference_classes.rst, docs/reference_wgpu.rst
This splits the wgpu API docs into two parts:
* A somewhat more guided document, that contains a list of all classes (sorted alphabetically) as well as an attempt to explain how things fit together, mentioning each class at leas once.
* All classes via autodoc.
Previously the "guide"  was mixed with the autodoc, but that did not really work, I think.
There is (a lot) of room for improvement, but it's a start.
=> Refactor docs a bit

docs/guide.rst
Add a note so that people don't get confused (like [I did](https://github.com/pygfx/wgpu-py/issues/261)) by trying to use the current main branch examples with the pip installable release version.
=> Add note about example version in repo vs pypi

wgpu/gui/base.py
=> Fix that handle_event cannot be overloaded to handle move and wheel events

wgpu/gui/glfw.py
On Win11 I consistently got an error (crash) when minimizing the glfw window. This fixes that, and it also fixes part of #255
=> Glfw don't draw if minimized

wgpu/backends/rs.py, wgpu/gui/base.py
Closes #256.
Turn vsync off when max_fps is high. This could also be a separate prop, but I suppose they sort of go hand in hand.
=> Ability to turn vsync off

wgpu/gui/qt.py
Closes #282
Tested the triangle_qt example:
Note:
While testing I used `pip uninstall PyQt6` and noticed that the package was still importable. I had to actually run `rm -rf .venv\lib\site-packages\pyqt6` to get rid of it. That was super annoying.
=> Ensure pyqt6 imports are correct

dev-requirements.txt
Closes: https://github.com/pygfx/wgpu-py/issues/293
This PR adds two missing dependencies to `dev-requirements.txt`
=> Add missing dev dependencies

setup.py
Closes: https://github.com/pygfx/wgpu-py/issues/291
This PR adds a small improvement to `setup.py` which makes it only include the release binary instead of including both the debug and the release version. The main benefit of doing so is to reducing package size.
I've also changed the glob (e.g., `*.dll`) into an explicit filename. My angle here is security. We know what the filename will be in advance and this way we can avoid collecting other binaries that we didn't expect to find. If you prefer the glob, I'm happy to revert :)
@Korijn I've also changed the `sys.platform` call to `platform.system`. `platform` is the currently recommended way to deal with platform-specific logic in python so I figured I would use the chance to update. That said, I don't feel very strongly about this and …
=> package only the release binary

README.md
This is a small test PR to check how the rules discussed in https://github.com/pygfx/wgpu-py/issues/301 are working.
The PR reformats the lines in the readme to be (roughly) 80 characters long.
=> STY: wrap lines in raw readme

wgpu/gui/offscreen.py
As discussed in https://github.com/pygfx/pygfx/pull/396 this PR adds a `_closed` flag that allows users to `.close()` an offscreen canvas. This makes the offscreen canvas behave a bit more like an offscreen canvas and allows unit-testing `gfx.Display` in pygfx.
=> make offscreen canvas closable

examples/tests/test_examples.py, wgpu/gui/offscreen.py
This avoids many types of overhead, like process creation, python interpreter startup, module importing, and wgpu device acquisition.
We use the runpy module here (and not exec) since it facilitates the use case quite well but also because it executes the code in a temporary module namespace.
With this change the full test suite runtime is improved as follows:
* Locally: 10.39s to 3.79s
* CI: 10.85s to 4.24s (but likely just a lucky shot, since software rendering is the bottleneck there, rather than initialization)
(Note: exactly the same change as https://github.com/pygfx/pygfx/pull/362)
=> Execute examples in the test process

tests/test_rs_basics.py, wgpu/backends/rs_helpers.py
The previous error prompt did not consider the situation when the error code is multiple lines.
For example:
It indicates that the error is at line 45, position -390, It is still difficult to quickly locate the wrong position.
This PR improves this, When the error is multiple lines, the code of error part and reason will be output directly, help locate quickly.
=> Improve the error prompt when wgsl code is multi line error

wgpu/gui/offscreen.py
We use `size` in all the GUI backends, but for some reason we used `width` and `height`  for the offscreen canvas 🤷 
This means that the validation examples in PyGfx have the default size instead of the custom one (if given). In particular the new validation example in https://github.com/pygfx/pygfx/pull/404 does not fit on the image :)
=> Fix offscreen size arg

wgpu/gui/auto.py, wgpu/gui/qt.py
This fixes a conflic with IPython's [`%gui qt`](https://ipython.readthedocs.io/en/stable/config/eventloops.html) magic (which is often used when running an interactive event loop in IPython)
```python
In [1]: %gui qt
In [2]: from wgpu.gui.auto import WgpuCanvas
```
```pytb
File ~/mambaforge/envs/microvis/lib/python3.10/site-packages/wgpu/gui/auto.py:37
35 for libname in ("PySide6", "PyQt6", "PySide2", "PyQt5"):
36     try:
---> 37         importlib.import_module(libname)
38         break
39     except ModuleNotFoundError:
File ~/mambaforge/envs/microvis/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
124             break
125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)
File …
```
=> fix: fix gui qt in ipython

.gitignore, conftest.py, examples/tests/test_examples.py, tests/test_gui_glfw.py, tests/test_rs_basics.py, tests/testutils.py, wgpu/backends/rs.py, wgpu/backends/rs_helpers.py
I ran into a case where the line info could not be found, and it printed the whole source. I fixed that, and refactored the code a bit along the way. I put the logic for parsing shader errorrs in a class to hold the different parts together. I also refactored the tests a bit, because the dedented code blocks made the tests very hard to read.
=> Improve wgsl error reporting

tests/test_gui_auto_offscreen.py, tests/test_gui_base.py, tests/test_gui_glfw.py, wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/qt.py, wgpu/gui/wx.py
=> Make canvases close when they get deleted

wgpu/gui/offscreen.py
Cleanup in offscreen.run was not sufficient. Call_later does not create tasks in the asyncio loop immediately, but we can use the handles returned by call_later to cancel.
=> Cancel callbacks in offscreen.run

download-wgpu-native.py
This enables downloading the experimental libwgpu_native.so for armv7. When the binaries are made to work upstream, they can directly be used in wgpu-py.
=> Enable downloading armv7 libs (raspberry pi)

wgpu/backends/rs.py, wgpu/resources/codegen_report.md
Closes #341
Just disable the check for now. We can enable it again when we update to the latest wgpu-native, because it has been fixed since.
=> Disable checking supported textures for getting preferred format

examples/shadertoy_blink.py, examples/shadertoy_circuits.py, examples/shadertoy_flyby.py, examples/shadertoy_glsl_flame.py, examples/shadertoy_glsl_fuji.py, examples/shadertoy_glsl_inercia.py, examples/shadertoy_glsl_mouse_event.py, examples/shadertoy_glsl_sdf.py, examples/shadertoy_glsl_sea.py, examples/shadertoy_glsl_stone.py, examples/shadertoy_liberation.py, examples/shadertoy_riders.py, examples/shadertoy_sea.py, tests/test_util_shadertoy.py, wgpu/utils/shadertoy.py
close #339 
The shadertoy tool now supports GLSL code.
When using GLSL, the built-in variables and entry functions have an additional alias (camel-case), which is consistent with the shadertoy website. In this way, we can use the code directly copied from the website almost without any modification.
I also added several examples of using GLSL.
=> Support GLSL in shadertoy

.github/workflows/ci.yml, .github/workflows/screenshots.yml, download-wgpu-native.py, examples/shadertoy_glsl_mouse_event.py, examples/tests/test_examples.py, wgpu/gui/offscreen.py, wgpu/utils/shadertoy.py
In #345 I ran into the doc build env not having installed numpy, and therefore failing the build. Numpy is not a dependency. So let's fix that.
=> Avoid unexpected numpy imports

wgpu/gui/qt.py
So when a WgpuWidget is embedded in a GUI, the winid is only obtained when needed (on the first draw). It looks like obtaining it initially puts the widget in a certain state (makes it native), and this results in problems when the widget is first created without a parent and then placed in the GUI.
----
```py
import PySide6
from PySide6 import QtWidgets
from PySide6.QtWidgets import QGridLayout, QBoxLayout
import pygfx as gfx
from wgpu.gui.qt import WgpuWidget
def main(canvas):
renderer = gfx.WgpuRenderer(canvas)
camera = gfx.NDCCamera()
scene = gfx.Scene()
scene.add(
gfx.Background(None, gfx.BackgroundMaterial((0.2, 0.0, 0, 1), (0, 0.0, 0.2, 1)))
)
triangle = gfx.Mesh(
gfx.Geometry(
indices=[(0, 1, 2)],
positions=[(0.0, -0.5, 0), (0.5, 0.5, 0), (-0.5, 0.75, 0)],
colors=[(1, 1, 0, 1), …
```
=> Only get initial windid on qt for canvas widgets

CHANGELOG.md, README.md, docs/gui.rst, docs/start.rst, setup.py, wgpu/gui/base.py
* Change RTD links to use the `stable` docs.
* Fix RTD.
* Also see https://github.com/vispy/jupyter_rfb/pull/72
=> Refer to stable rtd links

CHANGELOG.md, README.md, codegen/README.md, codegen/apipatcher.py, codegen/files.py, codegen/idlparser.py, tests/test_api.py, tests/test_rs_basics.py, wgpu/__init__.py, wgpu/backends/rs.py, wgpu/backends/rs_mappings.py, wgpu/base.py, wgpu/enums.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.idl, wgpu/structs.py
This updates wgpu-py to the latest WebGPU spec (represented in IDL). There are just a few minor changes and these mostly affect API that's not really "active" yet.
=> Update API to latest IDL

codegen/README.md, tests/test_util_core.py, wgpu/_coreutils.py, wgpu/backends/rs.py, wgpu/backends/rs_ffi.py, wgpu/backends/rs_helpers.py, wgpu/base.py, wgpu/gui/base.py
* This changes the binary, but there are no API changes that we need to adjust to.
* In the last release wgpu produces error messages that contain object id's, therefore the messages change. By filtering out these id's the messages are recognized as duplicates again.
=> Update to wgpu-native 0.17.2.1

wgpu/backends/rs_ffi.py
Closes #298
Tested manually by removing my wgpu-native binary, then commenting the linux check, and upping the required pip version.
=> Add warning about pip when binary is missing on linux

wgpu/backends/rs.py, wgpu/base.py
Until now we forced using the Vulkan adapter backend on Windows, because DX12 was less well support in the early days of wgpu-core.
* Without drivers installed, Vulkan cannot be used.
* I found that without drivers installed, not forcing the Vukan adapter runs (using D3D12), but not without flaws. At least better than Vulkan.
* At wgpu-core D3D12 is listed as having first class support, but ...
* The D3D12 backend (also with drivers installed) still has flaws, but that's ok, because ...
* I found that *with* drivers installed, auto-selection picks Vulkan.
* Eventually wgpu can also use D3D11 on older Windows versions that don't support Vulkan or Dx12.
* The situation around honoring the Nvidia panel settings are the same for all backends.
In summary, I think its fine to let wgpu select …
=> Stop forcing Vulkan on Windows

wgpu/gui/auto.py
When using `wgpu.gui.auto`, if PySide6 is already imported (and glfw is not) it will use the qt backend. Most typical use-case is IDE's with integrated event loops.
=> Refactor autogui selection to take imported backends into account better

wgpu/backends/rs.py
Best I can do for now for #352. Will dive deeper when we use a version of wgpu-native that uses the new canvas-context API (which does not have a concept for swap chains).
=> Provide extra tip for fixing monitor-swap error

docs/wgpu.rst, tests/test_rs_buffer.py, tests/test_util_core.py, wgpu/_coreutils.py, wgpu/backends/rs.py, wgpu/base.py
Feels like it should be possible because can do the same with enums (enum values in WebGPU *are* strings). Passing flags as strings can make code smaller by avoiding boilerplate.
=> Flags can be passes as str

wgpu/backends/rs.py, wgpu/gui/_offscreen.py
Two in-code todo's that I had on my list. I looked into them and only turned them into comments.
=> Update two comments

wgpu/backends/rs.py, wgpu/base.py, wgpu/resources/codegen_report.md
Nothing actually changes, but when we can push this further we'll have a good start. I mean, it takes time to navigate the header file to compose the functions and callbacks that are needed.
=> A small stab at get_compilation_info

wgpu/gui/auto.py
Addendum for #384. The code was trying all available backends, and the last one working was selected, instead of the first one.
=> Fix bug introduced in auto-gui refactor

wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/qt.py
See https://github.com/vispy/jupyter_rfb/pull/78 for the change that makes it work for jupyter_rfb (and the update to the event spec).
=> Add timestamp to events, and buttons to wheel events

wgpu/gui/base.py
=> Warn about refs in add_event_handler

examples/compute_noop.py
I found this example to be very helpful. 
It looks like the shader source didnt get changed to the new variable in some past refactor. 
This got it running for me and printing like the other 2 examples.
=> Fixup compute_noop.py numpy example

.github/workflows/ci.yml, tests_mem/test_mem.py, tests_mem/testutils.py, wgpu/backends/rs.py, wgpu/backends/rs_helpers.py, wgpu/gui/_offscreen.py, wgpu/gui/jupyter.py, wgpu/gui/offscreen.py, wgpu/resources/codegen_report.md
Closes #353
This adds tests, in a new folder so it won't interfere with the unit tests. The idea is basically, doing for each kind of object:
* Get how many objects we have of each kind.
* Create a bunch of objects of a specific kind.
* Make sure the counts are indeed up.
* Delete the objects. 
* Check that the counts are down.
Todo:
* No luck yet.
* Following up in #405
=> Add tests for object releasing

tests_mem/test_gui_glfw.py, tests_mem/test_gui_offscreen.py, tests_mem/test_gui_qt.py, tests_mem/test_meta.py, tests_mem/test_objects.py, tests_mem/testutils.py, wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/qt.py
Closes #406.
This modifies the tests in `tests_mem/` to help investigate potential memory leaks.
In normal mode, runs the test twice for each object, with two different object-amounts. In memory-usage-mode, runs 40 iterations with an object-count of 8, track memory usage at each iteration, and report that.
This work was originally about that last step, but in the end these memory measurement are pretty hard to interpret. They can sometimes be useful, and perhaps we can improve it in the future? But for now we only run those tests manually, not in CI.
----
Example:
```
test_release_adapter ...
49.1KB      0B      0B      0B      0B      0B      0B      0B  16.3KB      0B
16.3KB  16.3KB      0B      0B      0B      0B      0B      0B      0B      0B
0B  16.3KB      0B      0B      0B …
```
=> Measure memory usage during memtests

docs/guide.rst, examples/cube.py, examples/triangle.py, examples/triangle_glsl.py, tests/test_api.py, tests/test_gui_glfw.py, tests/test_wgpu_native_basics.py, tests_mem/test_objects.py, wgpu/backends/wgpu_native/_api.py, wgpu/base.py, wgpu/utils/device.py
The `canvas` argument in `request_adapter()` is not part of the WebGPU spec. It is an optional argument to `wgpuInstanceRequestAdapter()`, so it seemed like a good idea to make it possible to pass this argument. I initially made it a required argument, but in practice it is often set to None, because we often want to create a (global) device before we have a canvas.
This PR makes the argument optional, and puts it to the end of the arg to move it a bit out of sight, making the API feel more like WebGPU.
I want to get this into the 0.12.0 release, because our users will have to adjust their `request_adapter()` calls already.
=> Make canvas arg in request_adapter() optional

CHANGELOG.md, setup.py, wgpu/__init__.py
That's a lot of release notes 😅
=> Bump version to 0.12.0

wgpu/backends/wgpu_native/__init__.py
Meant to include this in  #429, but I forgot. No changes, except that `GetBindGroupLayout` raises an error instead of panicing when using an invalid index. For #423.
=> Update to wgpu-native v0.18.1.2

wgpu/gui/base.py, wgpu/gui/offscreen.py
Triggered by discussion in #430 and work in #429.
=> Improve gui docs

.github/workflows/ci.yml, download-wgpu-native.py, wgpu/backends/wgpu_native/__init__.py
This is a follow-up to the `0.18.1.3` release of wgpu-native. See https://github.com/gfx-rs/wgpu-native/pull/326#issuecomment-1840189996
- update wgpu-native version from `0.18.1.2` to `0.18.1.3`
- use "aarch64" for mac and linux instead of arm/arm64
Verified to work on Raspberry Pi OS (64-bit).
Resolves #187.
=> update wgpu-native version

download-wgpu-native.py, tests_mem/test_objects.py, tests_mem/testutils.py, wgpu/backends/wgpu_native/_api.py
We've found that in a rather particular use-case, when run in a Docker container, the process would (on some machines) die hard with a segfault. This was traced back to the call to `wgpuDevicePoll` from the `GPUPipelineLayout._destroy()`.
This PR:
=> Remove call to device._poll in _destroy methods

wgpu/gui/glfw.py
This is my guess at what helps with #446. However, I cannot reproduce the error (on MacOS nor Windows), so this is just a guess. Specifically, my guess is that the window is destroyed twice somehow, causing the access violation in the glfw lib.
=> Avoid using a destroyed glfw window

examples/compute_timestamps.py, tests/test_wgpu_native_query_set.py, tests_mem/test_objects.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
This PR adds the following functionality
- `device.create_query_set`
- `timestamp_writes` support in `command_encoder.begin_compute_pass`
- `command_encoder.resolve_query_set`
- add a new example (`examples/compute_timestamps.py`) that demonstrates the usage of the newly added features
Tests added
- `tests_mem/test_objects.py` to check release of `QuerySet`s
- `tests/test_wgpu_native_query_set.py` to test the newly added functionality
=> Implement timestamp QuerySet

examples/shadertoy_glsl_textures.py, examples/shadertoy_textures.py, wgpu/utils/shadertoy.py
Task for this PR:
***
as it seems to be the most common issue according to #426 (even though the filtered dataset has no shadertoys with inputs declared), the built in `iChannel0 .. 3` samplers are still used. They output 0 if nothing is attached to the channels. 
The Shadertoy website allows for various kinds of inputs, be it textures, cubemaps, buffers (other Shadertoys) or even webcam and audio. The most basic support will be to resolve "Unknown Variable iChannel0" by having a sort of default input of 0 that can be sampled. Texture input would be most useful, so that is my aim with this PR.
**So oddities I encountered:**
- only seems to work with unit8 (not float32)
- has to be flipped vertically?
**Some ideas I have had:**
- a `ShadertoyChannel` struct/class that can be used to hold …
=> Add texture input to Shadertoy util (iChannel0, ...)

wgpu/utils/shadertoy.py
While this doesn't show up in #426, I have seen this as an error at least once.
It should be simple to add, but understanding how the website implements it is a bit odd. The only reference I found is here: https://www.shadertoy.com/view/lsKGWV or the comment here: https://www.shadertoy.com/view/tlcfRB
So the implementation doesn't quite match the website but fits the literal definition. And it might be impossible to get a singular answer for this case, main idea being to avoid an "unknown variable" errors.
=> Add iFrameRate builtin to Shadertoy utility

README.md
This came up during #455 
I used a [search](https://github.com/search?q=%22import+wgpu%22+path%3A*.py&type=code&) and [dependands](https://github.com/pygfx/pygfx/network/dependents) to find some projects that use `wgpu-py`
=> List projects using wgpu-py

tests/test_gui_base.py, tests/test_wgpu_native_basics.py
As promised in #455.
Stuff that was covered via the shadertoy that this PR revives:
* glsl shaders 
* `begin_render_pass()` behavior for holding on to texture view objects long enough.
=> Update tests to re-implement coverage we had via shadertoy.

.github/workflows/ci.yml, examples/cube.py, examples/events.py, examples/triangle_auto.py, examples/triangle_qt.py, examples/triangle_qt_embed.py, examples/triangle_wx.py, examples/triangle_wx_embed.py, tests/renderutils.py, tests/test_diagnostics.py, wgpu/backends/wgpu_native/_api.py, wgpu/gui/glfw.py
When CI errors in a PR, it's sometimes convenient to trigger CI for `main` to see if its due to changes in the pr or something external that changed.
=> Enable manual CI trigger

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/other.md
With #462 you now get a choice when you create a new issue, but that choice only includes the "update wgpu" template 😅 . This PR adds other templates for bug reports, and a generic issue.
=> Update issue templates

tests/test_gui_base.py, wgpu/backends/wgpu_native/_api.py, wgpu/gui/base.py
Close #439
This should make things easier when building up code from scratch, or for people goofing around with canvases 😃
This works fine, and is tested for.
```py
from wgpu.gui.auto import WgpuCanvas, run
canvas = WgpuCanvas()
run()
```
This errors to prevent the base context class from being used, which results in confusing NotImplementeError later.
```py
from wgpu.gui.auto import WgpuCanvas, run
canvas = WgpuCanvas()
present_context = canvas.get_context()  # <--- raises exception
```
This previously raised an exception, but now logs a warning `No texture to present, missing call to get_current_texture()?`, which is a bit friendlier. We could technically also ignore the situation, but it does capture cases where a user uses old/wrong textures to render to for some reason.
```py
from …
```
=> Finetune behavior for bare canvas usage

docs/utils.rst, tests/test_diagnostics.py, wgpu/__init__.py, wgpu/_diagnostics.py, wgpu/backends/wgpu_native/_helpers.py
While hooking pygfx diagnostics on wgpu's nice system, I ran into a few small issues that this pr fixes:
* The `DiagnosticsBase` is now public API, so it can be subclasses without accessing `wgpu._diagnostics.Diagnostics`.
* Bools are now rendered using a checkmark/dash instead of 1 or 0.
* Better handling of very large ints (fall back to scientific notation).
* Check that a diagnostics name is an identifier, so that it can be reached via e.g. `wgpu.diagnostics.pygfx_caches`.
----
```
██ system:
platform:  Windows-11-10.0.22631-SP0
python_implementation:  CPython
python:  3.12.1
██ versions:
wgpu:  0.14.0
cffi:  1.16.0
glfw:  2.6.5
numpy:  1.26.4
pygfx:  0.1.17
pylinalg:  0.4.1
██ wgpu_native_info:
expected_version:  0.19.1.1
lib_version:  0.19.1.1
lib_path: …
```
=> Tweaks to diagnostics

wgpu/resources/webgpu.idl, wgpu/structs.py
Only affects docs a bit.
(Was looking into webgpu api and wanted to see if anything significant had changed. Barely a change, so I figured we might as well update it now, and thereby reduce noise in a future update.)
=> Update to latest IDL

docs/start.rst, examples/triangle_subprocess.py, tests/test_gui_base.py, tests/test_gui_glfw.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/_helpers.py, wgpu/gui/__init__.py, wgpu/gui/_gui_utils.py, wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/offscreen.py, wgpu/gui/qt.py, wgpu/gui/wx.py
Deals with #92. Probably won't entirely close it yet. 
Notes:
* This PR could be smaller if it'd just force x11 for glfw and qt, but in the process of trying out things, I also refactored a bit. These extra changes do make the code more "future ready" for when Wayland is supported better.
* Not sure what happens on more special linuxes like Raspberry Pi.
=> Wayland support by forcing x11

wgpu/backends/wgpu_native/__init__.py, wgpu/resources/wgpu.h
The wgpu-native project just had a new release. Hardly any changes required on our end.
=> Use wgpu-native 0.19.3.1

docs/gui.rst, wgpu/gui/_gui_utils.py, wgpu/gui/auto.py, wgpu/gui/glfw.py, wgpu/gui/qt.py
This PR overhauls the GUI backend selection, making it clearer (I hope), improving support for various use-cases, and making it easier to add support for specific use-cases.
=> Better support for interactive sessions

wgpu/backends/wgpu_native/_api.py
The warning was intended to help people who forgot to call `get_current_texture()`. But it looks like it does more harm then help, because when an exception happens in the draw function, the warning is printed below, making it easy to interpret that *that* is the error message. See e.g. https://github.com/pygfx/pygfx/issues/682
=> Don't warn in present()

docs/backends.rst, examples/compute_noop.py, examples/cube.py, tests/test_wgpu_native_basics.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/extras.py, wgpu/resources/codegen_report.md
The idea is to allow users to specify a specific GPU, which is particularly useful in a multi-GPU setup. The tricky bits are that the kinds of GPU's differ widely between systems, and there's a human choice in the loop. You don't want to prompt the user for input each time a script is run. Instead you want a simple way to present the user with the options on the current system, and do this once. Then in subsequent runs allow the user to specify one of these options using a string.
This PR simply makes it easier to enumerate adapters and get a description of each. The user is responsible for the selection mechanism, because this is always fuzzy, and we don't know the best approach yet, see #482. When we do, we will add a builtin selection mechanism to either pygfx or wgpu.utils.
=> Provide more control to select a specific GPU

.gitignore, wgpu/gui/wx.py
As already mentioned in #485, this issue fixes the missing event handler method call, by removing it. It also forces the wait-time calculation to be `>=1` and converts the wait-time to an integer after conversion to ms. This PR also adds the `.idea` file to the .gitignore.
=> WxWgpuWindow object has no attribute 'add_event_handler'

docs/start.rst
closes #493 
Adds "Cloud compute" section. Provides some basic guidance on the requirements for using WGPU in a GPU cloud compute environment, moves current Lavapipe docs to a subsection under "Cloud Compute"
=> Add GPU cloud compute info to docs

wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/jupyter.py, wgpu/gui/offscreen.py, wgpu/gui/qt.py, wgpu/gui/wx.py
Very convenient for downstream tools. But also to show stats (like cpu usage 😉).
Relates to #451, but I kept the scope minimal.
=> Implement canvas.set_title()

examples/compute_timestamps.py, tests/test_wgpu_native_query_set.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Implementing this because I'm looking into benchmarking. See #450 for the initial implementation for compute passes.
=> Support timestamp queryset for begin_render_pass()

wgpu/backends/wgpu_native/_helpers.py
In benchmarking for https://github.com/pygfx/pygfx/issues/763 it looked like the `proxy_func` is called a lot, so I figured that of it could be optimized it would be an easy win. It looks like the result is not really measurable, but nevertheless might be worth applying.
* Use a `deque` instead of a list.
* Move the capturing logic to the `ErrorHandler` class, so that the logic in the `proxy_func` becomes simpler. Also cleaner code imo.
* The above also means that the proxy_func closure only captures the `error_handler` object and no longer uses `self`.
=> Try to optimize proxy_func

examples/compute_noop.py, examples/compute_timestamps.py, examples/cube.py, examples/triangle.py, examples/triangle_glsl.py, tests/renderutils.py, tests/test_util_compute.py, tests/test_wgpu_native_basics.py, tests/test_wgpu_native_compute_tex.py, tests/test_wgpu_native_query_set.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md, wgpu/utils/compute.py
When setting bind groups, we often have code like this:
`render_pass.set_bind_group(0, bind_group, [], 0, 99)`
According to the WebGPU specification, this method has two overloaded different method signatures. 
The `dynamic_offsets` parameter has a default value of `[]`, and the last two parameters can also be omitted, indicate to direct passing of an array of dynamic offsets without copy.
The current usage is quite odd, as it requires users to provide parameters that are not actually used, which can cause confusion.
See: https://www.w3.org/TR/webgpu/#gpubindingcommandsmixin-setbindgroup
When setting a bind group, we can simplify the code to:
`render_pass.set_bind_group(0, bind_group)`
=> Update the default parameters of "set_bind_group()"

tests_mem/test_destroy.py, tests_mem/test_meta.py, tests_mem/test_objects.py, tests_mem/testutils.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
* Only device, queryset, buffer, and texture have these.
* Only actually does something for buffer and texture. But when wgpu-native implements it for device, we will do so automatically.
* See https://github.com/gfx-rs/wgpu-native/blob/33133da4ec5a0174cb21539ef2d3346f75200411/src/lib.rs#L2491-L2493
=> Implement destroy

wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Relates to #513 
This adds the API that I was reluctant to add, because its prone to the user (accidentally) using the mapped array after it becomes unmapped. However, there are potential performance benefits. I want us (and others) to be able to investigate its use. 
My proposal is to add it as an experimental and undocumented method. In time, when we know more about how useful it is, we can think about a public API for (something like) this.
Also adds an unrelated comment to `_poll()`.
=> Add experimental support for get_mapped_range

wgpu/backends/wgpu_native/__init__.py
Not now.
* Apply any necessary changes.
* Remove the FIXME comment if no further action is needed, or turn into a TODO for later.
=> New wgpu native

tests/test_wgpu_native_basics.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Don't call _tuple_from_tuple_or_dict, but go through an intermediate function for each possible type that knows the names of the arguments and what their defaults are.  No need to duplicate code. This fixes default arguments for Extend3d, Blend, and Origin3D.  Color (which requires all four components) is handled, too.  
Update _tuple_from_tuple_or_dict so that it can handle a list of default results.
Add lots of tests.
Fix one typo that is user visible.
Partial fix for #526.
=> Don't call _tuple_from_tuple_or_dict directly, but got thrown an intermediate function

tests/test_util_compute.py, tests/test_wgpu_native_buffer.py, tests/test_wgpu_native_query_set.py, wgpu/backends/wgpu_native/_api.py
Second (and final part) of bug fix for #526 
Modify `create_bind_group` to handle missing `offset` and `size.
Modify `timestamp=` argument in `create_xxxx_pipeline` so that either timestamp index can be missing.
More controversially (and I'll delete this if you want me to):
Modify `set_vertex_buffer`, `set_index_buffer`, and `clear_buffer` to mark the size as "not given by user" rather than making a guess as to what the size actually is.  
This doesn't fix any bugs, but seemed to be the right thing to do. In the normal cases, the current code works correctly. But if we ever end up with arrays of vertexes or the like, the current code won't work.
Added tests: 
Deleted `offset` and `size` from both compute and render pipelines.  
Added half-indexed timestamp arguments to make sure they gave …
=> Deal better with missing size and missing query index arguments

examples/imgui_basic_example.py, examples/imgui_multi_canvas.py, examples/imgui_renderer_sea.py, wgpu/utils/imgui/imgui_renderer.py
Exposes the context of `ImguiRenderer` so that it can be used for context switching. As far as I understand, this is required for rendering different UIs to multiple different canvases (added an example). Not sure if there's a better way to do this, welcome to suggestions! @panxinmiao 
tested in glfw & qt
=> Imgui multi canvas

tests/test_wgpu_occlusion_query.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Implementation turned out to be straightforward.
=> Implement occlusion query

examples/triangle_wx.py, wgpu/gui/wx.py
As discussed in #485, the `WxWgpuWindow` does not implement event handlers. Because of this, many features such as camera control and mesh picking will not work when pygfx is embedded in Wx.
This PR implements the keyboard, mouse, window resize and closed events. The implementation uses the Qt implementation as a template. However, there are some shortcomings:
- There is no pre-implemented method to convert a `keycode` to its string representation in Wx. I had to implement it myself. Some keys may not be mapped correctly. But it works with lower/upper keys using the modifiers and some special keys.
- At least on MacOS, the `wx.EVT_MOTION` event only fires on the canvas when a mouse button is pressed (like a drag motion). This might be a problem for FPS games. Perhaps it's possible to …
=> Implemented mouse, keyboard and window events for WxWgpuWindow

README.md
Let's focus on understanding the difference between it's (means *exactly* "it is": the apostrophe in English elides words together, e.g., /don't/ = "do not", /'n'/ = "and"). "Its" is the pronoun for the thing described (OpenGL), so companions to "its" also don't have apostrophes (his, her, his, hers, their). We're programmers: this syntax should not be hard for programmers to commit to knowledge. Even native English speakesr make this error far too often.
=> Update README.md "OpenGL is...showings its cracks" -> it's/its

codegen/wgpu_native_patcher.py, tests/renderutils.py, tests/test_wgpu_native_render.py, tests_mem/test_objects.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md, wgpu/structs.py
- Implement Render Bundle.
- Remove "return" statements in the `GpuDebugCommandsMixin` code.  
-- The functions are implemented in `libf`, so might as well call them. I have determined if they do anything or not. But we're prepared when they finally are implemented.
- Add tests.  
-- All rendering tests in `test_wgpu_native_render` are run both with direct rendering and render bundles.
-- Appropriate memory tests added.
@almarklein 
@Korijn 
I was uncertain about the best ways to handle the polymorphism in `GPUDebugCommandsMixin`, `GPUBinidngsCommandMixin` and `GPURenderCommandsMixin`.  In each case, we run identical code no matter what the type of `self`, except for calling a different library function.
I implemented this three different ways, in the hopes that you'd let me know which …
=> Implement Render Bundle and Tests

wgpu/utils/imgui/imgui_renderer.py
The pixel ratio of the canvas can change after the canvas has been created, this sets the pixel ratio on every render to make sure it's correct.
A better way to do this is if all canvases can have a callback when the pixel ratio changes. 
@panxinmiao 
closes #558
=> set pixel ratio in imgui renderer for each render

.github/workflows/cd.yml
Also remove the empty subdirs after moving the files out. This will prevent `twine` from failing.
(I already did the pypi release manually, this is for next release :) )
=> Final fix to cd

wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Remove all the duplicate _release code to its superclass
Add some comments.
Sorry for this rush of PRs.  I had a 14-hour plane flight and couldn't sleep.
=> Remove _release code that's duplicated 19 times.

tests/test_set_override.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Implement  [override constants](https://www.w3.org/TR/webgpu/#gpuprogrammablestage)
Allow entry_point to be elided if there is only one possible entry point.
Create functions for some common code in _api.py.
=> overrideable constants

docs/backends.rst, docs/guide.rst, tests/test_wgpu_native_basics.py, wgpu/backends/wgpu_native/__init__.py, wgpu/backends/wgpu_native/extras.py
As requested
Change request_adapter_trace to request_adapter.
=> Rename request_adapter_trace -> request_adapter

tests/test_set_override.py, tests/test_wgpu_vertex_instance.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Forgot to delete one _release
Allow most of tests in test_wgpu_vertex_instance to run even if multi-draw-indirect isn't available.  This will be useful in the future as we add more features. Also simplified the code a little bit.
Fixed one test where I believe naga's behavior is incorrect.  I updated the test to accept either naga's current behavior or the behavior of the JS implementation.
=> Fix some small errors

conftest.py, examples/tests/test_examples.py, examples/tests/testutils.py, tests/test_gui_glfw.py, tests/testutils.py, tests_mem/testutils.py, wgpu/backends/wgpu_native/_api.py
=> Fixes to testing

examples/cube.py, examples/gui_asyncio.py, examples/gui_auto.py, examples/gui_direct.py, examples/gui_glfw.py, examples/gui_qt.py, examples/gui_qt_embed.py, examples/gui_subprocess.py, examples/gui_trio.py, examples/gui_wx.py, examples/gui_wx_embed.py, examples/triangle.py, examples/triangle_glsl.py, tests/test_gui_glfw.py, tests_mem/test_gui_glfw.py, wgpu/gui/glfw.py
I observed the following warning when using glfw:
```
2024-10-02 16:13:41.233 python[40243:5114401] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-02 16:13:41.233 python[40243:5114401] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```
I checked that this happens inside `glfw.poll_events` and a quick Google suggests it is related to the latest MacOS Sequoia update. So nothing we can do on our end.
=> Tweaks to examples

codegen/apipatcher.py, codegen/hparser.py, codegen/idlparser.py, codegen/tests/test_codegen_result.py, codegen/utils.py, conftest.py, examples/README.md, examples/cube.py, examples/gui_asyncio.py, examples/gui_trio.py, examples/imgui_multi_canvas.py, examples/tests/test_examples.py, examples/triangle_glsl.py, tests/test_api.py, tests/test_set_constant.py, tests/test_wgpu_native_render.py, tests/test_wgpu_occlusion_query.py, tests/test_wgpu_vertex_instance.py, tests_mem/test_destroy.py, tests_mem/test_gui_glfw.py, tests_mem/test_gui_qt.py, tests_mem/testutils.py, wgpu/__pyinstaller/hook-wgpu.py, wgpu/_coreutils.py, wgpu/_diagnostics.py, wgpu/gui/auto.py, wgpu/gui/jupyter.py, wgpu/utils/__init__.py
Typos and grammar mistakes found by PyCharm. 
With one exception ("name" was used as a loop variable within another loop that also used "name" as a loop variable), there are no changes to code.  
I only took those changes that I thought were really typos or bad grammar.  PyCharm doesn't know how to use a/an before acronyms, and wants more commas than I do.
=> Nitpicky changes flagged by PyCharm

examples/gui_qt.py, examples/gui_qt_asyncio.py, examples/gui_qt_embed.py, wgpu/gui/qt.py
Closes #383
The example demonstrates how to use Qt to enable asyncio support.
=> Add example that uses PySide6 with asyncio compat

tests/test_wgpu_native_query_set.py, tests/test_wgpu_native_render.py, tests/test_wgpu_occlusion_query.py, tests_mem/test_destroy.py, tests_mem/testutils.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
https://www.w3.org/TR/webgpu/#depth-stencil-attachments
Make depth_stencil_attachment more closely follow the specification.  No longer do we need to specify stencil_xxx if it's a depth, and no need to specify depth_xxx if it's a stencil.  We only need to specify "color" if it's a "clear".
=> Make depth_stencil_attachment follow the spec

wgpu/_classes.py
Runnng the test suite from the terminal gives the warning shown below.  This makes this warning go away.
I haven't yet figured out a safe way to get rid of the other warning: ` /Users/fy/Pycharm/wgpu-py/wgpu/gui/glfw.py:557: DeprecationWarning: There is no current event loop`
```
================================================================================================== warnings summary ==================================================================================================
tests/test_gui_base.py::test_base_canvas_context
/Users/fy/Pycharm/wgpu-py/.venv/lib/python3.12/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <function GPUCanvasContext.__del__ at 0x102d51ee0>
Traceback (most recent call last):
File …
```
=> Eliminate warning in test suite

tests/test_wgpu_statistics_query.py, tests_mem/test_object_retention.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
As of wgpu 1.25, we no longer need to keep alive as many objects internally as we used to.  I have deleted several pieces of code that kept a copy of its arguments to that they wouldn't be released.  
The only exception is RenderBundleEncoder.  I have filed a [bug](https://github.com/gfx-rs/wgpu/issues/6433) about it.  
Added a test that agressively deletes objects even though they are needed by the GPU, just to make sure that things work correctly.
=> Only keep alive those objects that are necessary.

README.md, tests/test_wgpu_native_buffer.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py
FIXES #512 
If size of data isn't a multiple of 4, just round up.
Got rid of size argument to map_write, which no one was using.  Allow data to not be a multiple of 4 bytes.
Fixed a couple of typos, simplified some tests, added more tests.
The fix is essentially that used in the C WGPU API.
=> If data in create_buffer_with_data isn't a multiple of 4, just round up.

.pre-commit-config.yaml, README.md
I did this with their recommended setup where you specify a revision. 
You can alternatively set it up to use the users `ruff` binary with something like:
```
repos:
- repo: local
hooks:
- id: ruff
name: ruff
entry: ruff check .
language: system
```
This is opt-in and requires running `pre-commit install`. Otherwise the current manual workflow still applies.
=> Add pre-commit hooks for ruff

README.md, pyproject.toml
@fyellin [pointed out](https://github.com/pygfx/wgpu-py/pull/629#issuecomment-2433139825) that the current instructions in the README are not clear as to how a contributor may leverage `pre-commit` as a tool. 
I have included it in the `pip -e .[dev].` install as suggested and updated the reference in the README to point to the projects github landing page.
=> Include pre-commit in optional dependencies

codegen/tests/test_codegen_utils.py, codegen/utils.py
Closes #632
The logic to unfold signatures onto a single line was a bit crude and broke down when return type annotations are used. Basically, the end of the signature was detected by `line.endswith("):"):`. This fixes that by implementing the logic in a better way, following braces until the last one, and then searching from the final colon.
=> Fix codegen single-line logic for return types

wgpu/backends/wgpu_native/_api.py
When the creation of the canvas context fails, this results in extra errors, because the context does not have the `_surface_id` attribute. This fixes that.
=> Prevent extra errors when canvascontext creation fails

CHANGELOG.md, wgpu/_version.py
PRs to go first (their changes are already in the changelog):
* #635
* #636
=> Bump version

tests/test_set_constant.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Several wgpu-only features apply both to RenderPassEncoder and ComputePassEncoder.  Move some common code to their nearest shared ancestor (BindingCommandsMixin), but make sure that RenderBundleEncoder can't use it.
When ComputePassEncoder gets set_push_constant, it will be a one-line change.
=> More consolidation

docs/guide.rst, examples/cube.py, examples/gui_direct.py, examples/gui_subprocess.py, examples/imgui_backend_sea.py, examples/imgui_renderer_sea.py, examples/triangle.py, examples/triangle_glsl.py, tests/renderutils.py, tests/test_gui_base.py, tests/test_gui_glfw.py, tests_mem/test_gui.py, tests_mem/test_gui_glfw.py, tests_mem/test_gui_qt.py, wgpu/__init__.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/jupyter.py, wgpu/gui/offscreen.py, wgpu/gui/qt.py, wgpu/gui/wx.py, wgpu/utils/imgui/imgui_renderer.py
This does two things:
* Implement the changes in our `WgpuCanvasContext` to match with the new API in https://github.com/pygfx/rendercanvas/pull/21
* This means that wgpu keeps working with rendercanvas (after the above change) 
* Backport the changes in our gui backends.
* This means that `wgpu.gui` keeps working, so we can move to rendercanvas gradually.
=> Refactor present-method mechanic

wgpu/backends/wgpu_native/_helpers.py
=> Remove timeout in awaitable

wgpu/_diagnostics.py
Also nice to see the detailed versioning appear here.
```
██ versions:
wgpu:  0.19.2.post3+gd101e33.dirty
rendercanvas:  1.0.0.post8+ge9ba8f8
```
=> Add rendercanvas version to diagnostics

pyproject.toml
> The pytest anyio plugin is built into anyio. You don't need this package.
https://github.com/graingert/pytest-anyio/blob/default/pytest_anyio.py
=> remove unneeded pytest-anyio package

README.md, examples/tests/test_examples.py, wgpu/backends/wgpu_native/_api.py
port of https://github.com/pygfx/pygfx/pull/827
=> Improve state of the art for screenshot testing

.github/workflows/ci.yml, .github/workflows/screenshots.yml, docs/conf.py, examples/compute_timestamps.py, examples/gui_asyncio.py, examples/gui_direct.py, examples/gui_trio.py, examples/tests/test_examples.py, tests/test_wgpu_native_buffer.py, tests_mem/testutils.py, tools/build_all_wheels.py, wgpu/backends/wgpu_native/_api.py
this was missed since #350 and caused a panic. wgpu-py now has a different solution but this seems to be the root cause in shadertoy (which used the same ci workflows) https://github.com/pygfx/shadertoy/pull/37#issuecomment-2594147817
this PR is mostly to try if CI is still happy here.
=> use default lavapipe for screenshot

tools/download_wgpu_native.py, tools/hatch_build.py
Ref #666
@hmaarrfk Would this simple tweak allow the feedstock to drop another patch?
Not sure if there's an env var that we can check that a conda build is in progress. But in any case I imagine you can set an env var in the recipe.
=> Allow disabling downloading lib when creating wheel

examples/imgui_renderer_sea.py, wgpu/utils/imgui/__init__.py, wgpu/utils/imgui/imgui_renderer.py, wgpu/utils/imgui/stats.py
This pull request introduces an Imgui-based Stats component, inspired by `pygfx.Stats`. It offers three modes: fps/ms (text), fps (histogram), and ms (plot_lines), which can be toggled by clicking. 
Its performance surpasses that of `pygfx.Stats`; replacing `pygfx.Stats` with this component in the animation example can boost the frame rate by several dozen fps, aiding in obtaining more accurate performance results.
https://github.com/user-attachments/assets/96675875-1b92-41d5-8ddd-8bcd75b9e3d8
=> Add Imgui based Stats component

wgpu/utils/compute.py
My fork was a mess, cleaner PR this time. Allow passing override constants to the `compute_with_buffers()` helper.
=> pass constants to compute helper

wgpu/utils/imgui/imgui_renderer.py
I found that the mouse wheel operation on imgui is reversed.
A simple fix.
I think because we take the reversed value here:
https://github.com/pygfx/wgpu-py/blob/8b61daa061755ae0c3161a1a2f9bf94eb17042f6/wgpu/gui/glfw.py#L464
=> Fix imgui scroll event

tests_mem/test_gui.py, tests_mem/testutils.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
I did some experiments and this is a relatively easy way to improve performance by about 20%, going from ~24 to ~30 fps on fullscreen window on a 4k monitor on my M1 MacBook.
Tricks applied:
* ~~re-use the target texture~~ -> let's not for memory concerns, also seems to not help much.
* Reuse (and share) the buffer needed to copy the texture data to the CPU.
* Avoid a data-copy when bytes-per-row is not a multiple of 256.
* ~~use numpy for copying~~ does not seem to help much, and would introduce a new optional dependency.
We can go much faster, but for that we need to have our async stuff sorted out better.
More details here: https://github.com/pygfx/rendercanvas/issues/40#issuecomment-2714064032
=> Improve performance for 'bitmap' render method

CHANGELOG.md, wgpu/_version.py, wgpu/backends/wgpu_native/__init__.py
I forgot that in wgpu-py we write the release notes in a file in the repo instead of in the GH release page. Maybe we should pick one approach to do consistently in all repos of the pygfx project.
Also bumped the version, sot that it includes the new release notes.
=> Release notes

wgpu/backends/wgpu_native/_ffi.py
I updated my fork and local branches after the #673 merge and redownloaded the lib using the script. Got hit with an `pycparser.plyparser.ParseError: <cdef source string>:11:1: Illegal character '\r'` on my windows machine.
here is a fix, but likely not the best (still error prone due to the duplicated code for reading the headers).
Also maybe we can get a Windows runner for CI?
=> fix newlines

docs/backends.rst, tests/test_wgpu_vertex_instance.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/extras.py, wgpu/resources/codegen_report.md
Six months after the initial pull request. The bug in the backend that prevented `multi_draw_indirect_count` and `multi_draw_indexed_indirect_count` from working has been fixed and brought in wgpu-py.
=> Add multi_draw_indexed_indirect_count and multi_draw_indirect_count

tests/test_set_override.py
Add tests that verify that workgroup sizes can be dynamically modified using override
=> Verify that override variables can be used for workgroup sizes and array lengths

tests/test_api.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Bug #695 
Use GPUAdapterInfo.  Add subgroup_min_size and subgroup_max_size.  
For now, we can use default sizes from Spec, but eventually these will be available in the C WGPUAdapterInfo.
=> Use GPUAdapterInfo.

codegen/apipatcher.py, codegen/idlparser.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py
closes #696 
found where the type hints can be added in codegen, had to work through a bunch of edge cases. Will see if these cases can be added to already existing utils.
also not sure if `-> None` is really wanted everywhere.
still in progress... hopefully I can get this done early next week.
as for the 2nd question in the issue, I looked through some ideas with stub classes in mypy, .pyi files and even using `if "TYPE_CHECKING"` to import the autobackend. But doesn't feel like that solves the issue if having the "go to declaration" button go to the implementation - I might keep this an option issue.
=> Add return type hints

wgpu/utils/imgui/imgui_backend.py, wgpu/utils/imgui/imgui_renderer.py
With the recent change in `rendercanvas` where it draws during resize (https://github.com/pygfx/rendercanvas/pull/70), there are draws while the event for that resize has not been emitted yet. This tweaks the imgui adapter to get the real physical size, instead of relying on the resize event.
=> Imgui get up-to-date framebuffer size

wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/resources/codegen_report.md
Ref https://github.com/pygfx/pygfx/issues/642
This PR improves the logic for `canvas_context.get_current_texture()`, especially with regard to window resizing. This covers a use-case where on some Linux systems the texture status is 'outdated`.
One problem is that we can get in a situation where we cannot successfully obtain a texture for the surface. There are a few options:
* I looked into introducing a special error type that can be used to "cancel" a draw, to be caught by the scheduling logic. But this is tricky for various reasons, so I decided against it.
* Define a special error type that the caller of `get_current_texture()` must catch. The downside is that it changes the API of the method compared to the WebGPU spec.
* Use the texture regardless of it being in an error state. I …
=> Improve get_current_texture for window resizing

wgpu/_classes.py, wgpu/resources/codegen_report.md
In #699 the `adapter.info` prop returned an `AdapterInfo` instance instead of a dict. This PR updates the `__repr__` so that use-code that did  something like the below will still produce something meaningful:
```py
for a in wgpu.gpu.enumerate_adapters_sync():
print(a.info)
```
=> Give AdapterInfo a repr

codegen/apipatcher.py, codegen/idlparser.py, wgpu/_classes.py, wgpu/resources/codegen_report.md
follow up to #697 
goal is to add type annotations to properties in `_classes.py` via codegen. 
A lot of properties resolve to simple `int` or `str` python types while others are enums.
Will look into expanding `resolve_type` where it's needed or find better workarounds for features/limits. I am not 100% sure how type hints get inherited from these stubs, as there have been changes every single python release.
=> add type hints for properties

examples/imgui_renderer_sea.py, wgpu/utils/imgui/stats.py
The Stats component now supports displaying additional data, making it easier for users to quickly present custom information in the UI. 
As shown in the following picture (spp):
Additionally, the component's size now automatically adjusts based on its content.
=> Support extra data in stats

wgpu/utils/imgui/imgui_backend.py, wgpu/utils/imgui/imgui_renderer.py
See: https://github.com/pygfx/wgpu-py/pull/711#issuecomment-2853486448
We also need to update the `display_size` in `draw_data`, as it is used when setting the camera state.
I noticed that this change was made in #706, but I couldn’t really tell the difference. 🤔 
Also, in theory, if we update the size value every time the render method is called, we shouldn’t need to handle the canvas `on_resize` event anymore — but it seems we still can’t remove that event handler.
=> Set the size via `imgui.io` instead of using the `psize` parameter of the render method.

examples/compute_textures.py
Adds example that shows how to setup textures and a pipeline to run a compute shader on the textures to convert from RGBA -> YCbCr and also read the output textures.
Questions:
1. Would be nice to plot this directly with wgpu but is that easy to do :laughing: , or I can just leave the commented out fpl code at the bottom.
2. How do you debug shaders, I was doing a lot of things like this where workgroup invocations are performed on 8x8 blocks of the texture. Writing the workgroup_id value to the texture to make sure I've written my for loops correctly and structured my invocations correctly, looking at the output values and the image as well.
```wgsl
var L = f32(wid.x) + f32(wid.y);
// store luma channel
textureStore(tex_y, pos, vec4<f32>(L, 0, 0, 0));
```
=> add compute texture example that converts RGBA -> YCbCr

examples/imgui_cmap_picker.py, pyproject.toml, wgpu/utils/imgui/imgui_backend.py
Close #723 
Note:  imgui 1.92 introduced some changes to font-related functionality, and downstream projects, as well as some examples in pygfx, may need to be adapted accordingly by following the [official guidelines](https://github.com/ocornut/imgui/releases/tag/v1.92.0).
=> Update imgui to v1.92

wgpu/backends/wgpu_native/_api.py
This was an upstream bug that got fixed a while ago: https://github.com/gfx-rs/wgpu-native/issues/412
Now seems to work without the call to release
=> Remove additional call to `._release`

codegen/apipatcher.py, codegen/idlparser.py, examples/cube.py, examples/triangle.py, wgpu/_classes.py, wgpu/_coreutils.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/extras.py, wgpu/structs.py
=> More type improvements
