README.md, azure-pipelines.yml, dev-requirements.txt, setup.py, tests/test_api.py
**Important: merge #2 first!**
* Azure-pipelines CI script for Mac OS, Windows and Linux
* Checks code is black in `wgpu`, `tests` and `examples`
* Runs test suite, once in development mode and once after installing the built wheel to catch any packaging issues
* Merges all 6 test runs into a single overview
* Builds wheels and publishes them so they can be downloaded
* For tagged commits on master
* Creates (draft) GitHub releases
* Uploads wheels to PyPI
You can view a recent run here: https://dev.azure.com/korijn/wgpu-py/_build/results?buildId=22&view=results
Make sure to have a look at "Tests" and "Artifacts" as well to see how those work in Azure pipelines.
You'll need to go through some motions to set up Azure Pipelines for your personal repository and grant the required …
=> Azure pipelines

examples/triangle_js.py, examples/triangle_qt.py, wgpu/gui/base.py, wgpu/gui/flexx.py, wgpu/gui/qt.py
Also some tweaks and improvements to the qt gui backend. Looked briefly into SDL2, but pysdl2 looks unmaintained.
=> implement glfw gui backend

README.md, examples/triangle.py, examples/triangle_js.py, examples/triangle_qt.py, examples/triangle_tk.py, wgpu/gui/glfw.py, wgpu/gui/qt.py, wgpu/gui/tk.py
* Adds `gui/tk.py` implementing a `WgpuCanvas`.
* Add tk example.
* Refactor triangle examples so they all use the same code from a shared `triangle.py`.
=> Add tk gui support

azure-pipelines.yml
* Make release job run on py3.6
* Make sure the sdist is also pushed to pypi
* Don't push the linux build to pypi :(  pypi is mean to us and only acceps manylinux wheels
=> try make CD to pypi work

azure-pipelines.yml
* Trigger builds for master branch and tags that start with `v`
* Only run release job if branch name matches tag name (that's how we can tell the build was triggered by a tag)
=> Release for tags only

azure-pipelines.yml, dev-requirements.txt
Closes #37 and the `git restore` issue
Pinned pip to <20.0.0 because it seems to be broken?
=> Windows 32 bit builds

README.md, examples/triangle.py, examples/triangle_glfw.py, examples/triangle_glfw_asyncio.py, examples/triangle_qt.py, examples/triangle_tk.py, wgpu/gui/glfw.py
=> Get rid of asyncio from the examples. Add one asyncio+glfw example.

azure-pipelines.yml
Trying the new pip build as recommended here: https://github.com/pypa/pip/issues/7626#issuecomment-578092508
=> try new pip

wgpu/backend/rs.py
=> Ensure correct lifetime of sub-structs that are referenced as pointers

.gitignore, dev-requirements.txt, setup.py, wgpu/__pyinstaller/__init__.py, wgpu/__pyinstaller/conftest.py, wgpu/__pyinstaller/hook-wgpu.py, wgpu/__pyinstaller/test_wgpu.py, wgpu/backend/rs.py
Don't merge until we have approval and alignment with @bjones1 at https://github.com/pyinstaller/pyinstaller/pull/4662
=> PyInstaller runtime hook and test

wgpu/backend/rs.py
=> WIP: Progress

tests/test_compute.py, tests/test_gui_glfw.py, tests/test_rs_compute_tex.py, tests/test_rs_render.py, tests/test_rs_render_tex.py, wgpu/base.py, wgpu/utils/_compute.py
* With these, I can run all tests on Linux, with my NVidia drivers.
* With Intel drivers, all tests work except the `test_compute.py`.
* With Intel drivers the 3 disabled texture render tests actually work!!
=> Fixes for Linux

download-wgpu-native.py
To support https://github.com/Korijn/wgpu-bin/pull/8
=> Support wgpu-native debug builds

examples/cube_glfw.py
This serves two purposes:
* Having a somewhat more advanced example (including texturing) helps new users.
* We can use this to investigate why we get segfaults when we use multiple bind groups in certain ways.
=> Add textured cube example

wgpu/_coreutils.py, wgpu/backends/rs.py
Will need to wait for a new version/build of wgpu-native.
=> Getting version and logging messages from wgpu-native 

tests/test_api.py, wgpu/backends/rs.py, wgpu/base.py
=> A few small tweaks

CHANGELOG.md
=> Use standardized changelog format

examples/triangle_subprocess.py
Doing this is probably a bad idea in many cases. But I may have a use-case where this might be very handy :)
=> Add example that draws into the window of a subprocess

wgpu/backends/rs.py, wgpu/backends/rs_helpers.py
=> Fix for pypy not having memoryview.contiguous

CHANGELOG.md, codegen/README.md, codegen/idlparser.py, docs/reference_wgpu.rst, tests/test_rs_render.py, wgpu/backends/rs.py, wgpu/base.py, wgpu/enums.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.idl, wgpu/structs.py
For good measure. Only minor changes that barely affect our API.
=> Update to latest Webgpu

setup.py
=> Exclude codegen from package

.github/workflows/ci.yml, docs/guide.rst
=> Our Pyinstaller hook should now just work

README.md, setup.cfg, setup.py
=> add extras, tweak lint config to exclude .venv, update README

wgpu/gui/glfw.py
=> GLFW: prevent error for special keys not in our key map

wgpu/gui/glfw.py
Add (configurable) FPS limiting to the GLFW backend.
=> GLFW: max_fps

wgpu/gui/wx.py
Closes #209, and also adopts (configurable) fps limiting.
=> WX: max_fps (and fix request_draw on Windows)

wgpu/gui/glfw.py
* Catch and print exceptions in glfw callbacks.
* Fix modifiers for pointer events.
=> Glfw fixes

wgpu/gui/glfw.py
=> Use same lazy init approach in glfw as in qt

docs/reference_gui.rst, tests/test_gui_auto_offscreen.py, tests/test_gui_base.py, tests/test_gui_glfw.py, wgpu/gui/__init__.py, wgpu/gui/base.py, wgpu/gui/glfw.py, wgpu/gui/jupyter.py, wgpu/gui/offscreen.py, wgpu/gui/qt.py
=> Implement WgpuAutoGui mixin to avoid duplicating code

.github/workflows/ci.yml, download-wgpu-native.py, wgpu/__pyinstaller/test_wgpu.py, wgpu/backends/rs.py, wgpu/gui/glfw.py
This is (again) due to the fact that the meaning of screen space depends on the platform. We had a trick to detect the meaning, and in this PR we use the result to fix the pos in mouse events.
~Would be good if someone on Windows/Linux with a hidpi screen could check that the positioning still works well there. E.g using pygfx's picking_points.py example.~ Done :)
=> Glfw mouse position fix

README.md
=> add screenshot

wgpu/gui/qt.py
So, can use "OrbitControls" , etc. on "QWgpuWidget"
=> 'QWgpuWidget' adds support for events, and delegate events of QWgpuCanvas' to subwidgets

CHANGELOG.md, codegen/rspatcher.py, docs/conf.py, docs/reference_wgpu.rst, examples/compute_noop.py, examples/cube.py, examples/triangle.py, examples/wgpu-examples.ipynb, tests/renderutils.py, tests/test_compute.py, tests/test_gui_base.py, tests/test_gui_glfw.py, tests/test_rs_compute_tex.py, tests/test_rs_render.py, wgpu/backends/rs.py, wgpu/backends/rs_mappings.py, wgpu/base.py, wgpu/enums.py, wgpu/gui/offscreen.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.idl, wgpu/structs.py, wgpu/utils/_compute.py
See the changelog (first file in the diff).
=> Update to latest WebGPU spec

README.md, docs/guide.rst, docs/index.rst, docs/start.rst, wgpu/__init__.py
Small textual changes to clarify the relation with WebGPU a bit. I think this does not clash with #263.
=> Minor doc tweaks

.github/workflows/ci.yml, .github/workflows/screenshots.yml, README.md, examples/tests/test_examples.py, examples/triangle_wx.py, examples/triangle_wx_embed.py
=> Reorganize example testing

tests/test_rs_basics.py, wgpu/backends/rs_helpers.py
Related #278 #279 
Currently, wgsl error tips only support 'Parsing error'.
This PR adds support for "Validation error".
Like the following:
=> wgsl error tips supports validation error

README.md
=> Fix type on README.md

wgpu/gui/qt.py
Fixes https://github.com/pygfx/pygfx/issues/372.
=> Fix using .draw_frame on qt canvas

README.md
=> Add note on linux compatibility of binaries

wgpu/gui/qt.py
Closes https://github.com/pygfx/pygfx/issues/368
=> Prevent Qt warning about setting dpi awareness

wgpu/gui/base.py
=> Ignore errors in call to close from __del__

wgpu/backends/rs_ffi.py
This makes life easier for  users/devs who have a dev-install of wgpu-py.
=> Give hint when native lib is outdated

CHANGELOG.md, wgpu/__init__.py
Intended to be merged after #343
=> Bump version

.github/workflows/ci.yml, examples/tests/test_examples.py, tests/testutils.py
Also removed the Lavapipe ppa.
=> Enable example screenshot tests again

wgpu/gui/qt.py
=> Fix getting qt version on pyqt

tests/test_rs_compute_tex.py, tests/test_rs_render_tex.py, wgpu/backends/rs.py
(should do that in pygfx)
Let's wait with merging until we've updated pygfx accordingly.
=> Don't enable features by default 

.github/workflows/ci.yml, .github/workflows/screenshots.yml, docs/wgpu.rst, tests/test_gui_auto_offscreen.py, wgpu/backends/rs_helpers.py
See commit titles.
(I've checked out some of the TODO's in the code and picked up the trivial ones.)
=> Bit of cleanup

codegen/apipatcher.py, codegen/idlparser.py, docs/guide.rst, docs/start.rst, docs/utils.rst, docs/wgpu.rst, docs/wgpu_enums.rst, docs/wgpu_flags.rst, docs/wgpu_structs.rst, wgpu/backends/rs.py, wgpu/base.py, wgpu/resources/codegen_report.md, wgpu/structs.py
Improve / clean the docs and API a bit.
I'll have a look at the compilationInfo stuff separately.
=> Clean docs and (unused) API

wgpu/gui/offscreen.py
When working on a unit test for canvases in #403, I realized that the behavior in `gui/offscreen.py` was a bit weird. We use asyncio for the event loop, but we also make `run()` behave as if there is no loop. We've had to change this code one or two times because of lingering refs due to the `call_later`.
This PR removes the event loop entirely, and fakes `call_later` a bit to make examples that use it still behave more or less as can be expected.
=> Remove asyncio from offscreen gui

.github/workflows/ci.yml, docs/start.rst, setup.py, tests/test_gui_auto_offscreen.py, tests/test_gui_base.py, tests/testutils.py, tests_mem/test_gui_offscreen.py, tests_mem/testutils.py
=> Support python 3.8-3.12, and pypy

examples/triangle_glsl.py
this seem to have been missed in #429 
passed all test and examples
=> Fix triangle_glsl.py example

.github/ISSUE_TEMPLATE/update-wgpu.md
I used github's UI for adding an issue template for updating wgpu. This may help streamline the update process.
=> Update issue templates

wgpu/backends/wgpu_native/_api.py
Add two fields to adapter-info, perhaps they are useful in detecting GPU's.
=> Add more adapter info

wgpu/gui/glfw.py, wgpu/gui/qt.py
xref: https://github.com/pygfx/pygfx/pull/731
=> Make modifiers and buttons tuples for immutability

wgpu/backends/wgpu_native/_api.py
Fix #499 
Add code from create_compute_pipeline to create_render_pipeline
=> Allow create_render_pipeline to use AutoLayout

wgpu/backends/wgpu_native/_api.py
Topology defaults to "triangle-list", as per spec.
=> Allow topology to be elided, as per spec.

CHANGELOG.md, docs/start.rst, docs/wgpu.rst, tests/testutils.py, wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/enums.py, wgpu/resources/codegen_report.md, wgpu/resources/webgpu.idl
Only two changes really:
* `adapter.request_adapter_info()` -> `adapter.info`.
* A new feature name (not yet supported by wgpu-native).
=> Update to latest idl

wgpu/_classes.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/_helpers.py
Better document what is expected of incoming data. Relates to https://github.com/pygfx/pygfx/pull/795 a bit.
=> Improve docstrings related to data

examples/imgui_cmap_picker.py
I'm doing a bunch of imgui stuff now which has finally forced me to learn how to use wgpu directly :smile: . I can keep adding more examples if you're interested. There are certain imgui things which are backend-specific, for instance there are many examples out there on using textures with opengl but not with wgpu-py so it took me a while to figure out how to implement something like this.
https://github.com/user-attachments/assets/be28e2a0-72a9-4755-945d-f1cb48329c81
draft because I want to clean it up a bit and add comments
=> cmap picker with imgui

wgpu/gui/offscreen.py
=> Fix offscreen imgui

examples/imgui_cmap_picker.py
forgot to fix and example after #539, and the texture sampler isn't actually used in this example so remove that as well
=> Fix example and remove unused texture sample

setup.py
FIXES #549.
Needed to switch to a different 1-argument get_platform()
=> Get different get_platform

dev-requirements.txt, pyproject.toml
See https://github.com/pygfx/wgpu-py/pull/551#issuecomment-2275686951.
=> Remove wheel from built requirements

CHANGELOG.md, wgpu/__init__.py
I'm off-grid from Friday-Sunday. @Korijn feel free to merge and push a tag to make a release. Otherwise we can do it on Monday.
=> Bump again

.github/workflows/cd.yml, CHANGELOG.md, wgpu/__init__.py
=> Fix pypy release in cd

CHANGELOG.md, wgpu/__init__.py
For the update to wgpu-native (and new win aarch64 build).
=> Bump version to 0.18.0

.github/workflows/ci.yml, .github/workflows/screenshots.yml, .readthedocs.yaml, docs/start.rst
Ref https://github.com/fastplotlib/fastplotlib/pull/651
=> Fix install of mesa drivers

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml, wgpu/__init__.py, wgpu/_version.py
Same as Pygfx did in https://github.com/pygfx/pygfx/pull/861
=> Add extra version info on dev installs

README.md
Minor language typo in the README intro :)
=> Fix small typo in README intro

tools/hatch_build.py
=> do not confound STDERR and STDOUT

docs/conf.py
Not sure why it was disabled ...
=> Alwats use rtd theme

pyproject.toml, wgpu/utils/imgui/imgui_renderer.py
Its a little frustrating to be forced to update for such a small thing, especially when trying to troubleshoot other compatibility issues.
=> Ensure that wgpu is compatible both with imgui 1.6.0 and older

wgpu/gui/qt.py
See https://doc.qt.io/qt-6/highdpi.html
=> Stop setting AA_EnableHighDpiScaling since Qt Says it is not needed

wgpu/backends/wgpu_native/_helpers.py
=> Improve error handling

wgpu/_coreutils.py, wgpu/backends/wgpu_native/_ffi.py
For the conda-forge packages I package wgpu-native myself and install them in the "system" libraries.
This should continue to allow you to use the "wheel" vendored headers but then also look for the headers in the "system" locations.
I've been dragging on a simpler (less upstreamable) version of this patch for about a year but I'm hoping I don't have to with this addition.
=> Add patches for conda compatibility

examples/imgui_cmap_picker.py
A simple patch to account for an API change in Dear ImGui Bundle (I am the author of the imgui python bindings in imgui-bundle).
=> examples/imgui_cmap_picker.py - update for imgui bundle 1.6.2

examples/imgui_renderer_sea.py, wgpu/utils/imgui/stats.py
Let Stats render automatically.
=> Auto render Stats 

CHANGELOG.md, wgpu/_version.py, wgpu/backends/wgpu_native/__init__.py
=> Update to latest wgpu-native (and bump version)

docs/backends.rst, tests/test_wgpu_native_query_set.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/extras.py, wgpu/resources/codegen_report.md
Implement writeTimestamp()
Make timestamp testing more extensive.  Test timestamps using both rendering and computing.  Also test all new versions of writeTimestamp().
=> Implement wgpu extension writeTimestamp()

wgpu/gui/qt.py
Closes https://github.com/pygfx/pygfx/issues/1054
=> Fix constructing QApplication for PyQt6

codegen/wgpu_native_patcher.py, wgpu/backends/wgpu_native/_api.py, wgpu/backends/wgpu_native/_mappings.py
Ref https://github.com/pygfx/pygfx/issues/642
=> Improve reporting when context.get_current_texture() fails
